volumes:
  mongodb:
  server:

services:
  mongo:
    container_name: ${DB_NAME}
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db

  server:
    container_name: ${SERVER_NAME}
    build:
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - server:/build
    depends_on:
      - mongo